name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependancies 
      run: npm install
    - name: Execute unit tests 
      run: npm run test:unit
    - name: Display softuni username
      run: echo 'bigboss008'

  run_ui_tests:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependancies 
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Start app in background
      run: npm run start &
    - name: Execute UI tests 
      run: npm run test:ui

  deploy:
    needs: run_ui_tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true